apiVersion: apps/v1
kind: Deployment
metadata:
  name:  router-deployment
  labels:
    name:  router-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app:  router
    spec:
      containers:
      - image: router:v1
        imagePullPolicy: IfNotPresent
        name:  router-server
        resources:
          requests:
            cpu: "250m"
            memory: "250M"
          limits:
            cpu: "500m"
            memory: "500M"
        livenessProbe:
          httpGet:
            path: /api/status/healthz
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/status/readyz
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 5
        ports:
        - containerPort:  3000
          name:  router-server
      